import type { EventData } from "./types";

export const MOCK_EVENT: EventData = {
  eventName: "NEON OASIS vol.04",
  date: "2026-06-28",
  startTime: "22:00",
  endTime: "05:00",
  venue: "Circus Tokyo",
  address: "東京都渋谷区円山町2-16",
  performers: "NABLUS / mno / sara.jp / KEINA",
  description:
    "エレクトロニックミュージックイベント。ネオンカラーに彩られた空間で最高の一夜を。",
  url: "https://example.com/neon-oasis",
  confidence: 0.92,
  category: "DJ Event",
  thumbnailColor: "#F3C9B6",
  thumbnailLabel: "NEON\nOASIS",
};

export const MOCK_HISTORY: EventData[] = [
  {
    eventName: "FOLD / UNFOLD",
    date: "2026-06-15",
    startTime: "11:00",
    endTime: "20:00",
    venue: "PARCO MUSEUM TOKYO",
    address: "東京都渋谷区宇田川町15-1",
    performers: "",
    description: "現代アートとデザインの境界を探る展示会。",
    url: "",
    confidence: 0.9,
    category: "展示会",
    thumbnailColor: "#C8E6CD",
    thumbnailLabel: "FOLD/\nUNFOLD",
  },
  {
    eventName: "SUNSET LOOP",
    date: "2026-06-21",
    startTime: "16:00",
    endTime: "21:00",
    venue: "横浜赤レンガ倉庫 特設会場",
    address: "神奈川県横浜市中区新港1-1",
    performers: "Yogee New Waves / never young beach / SIRUP",
    description: "夕暮れの港を舞台にしたライブイベント。",
    url: "",
    confidence: 0.88,
    category: "ライブイベント",
    thumbnailColor: "#EFD4D4",
    thumbnailLabel: "SUNSET\nLOOP",
  },
  MOCK_EVENT,
  {
    eventName: "夜想曲 NOCTURNE",
    date: "2026-07-12",
    startTime: "14:00",
    endTime: "21:00",
    venue: "日比谷野外大音楽堂",
    address: "東京都千代田区日比谷公園1-5",
    performers: "青葉市子 / haruka nakamura / 原摩利彦",
    description: "夏の夕暮れに贈るアンビエントミュージックフェスティバル。",
    url: "",
    confidence: 0.88,
    category: "音楽フェス",
    thumbnailColor: "#C5B0F4",
    thumbnailLabel: "夜想曲",
  },
];
